<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Maay-dev] new bug in indexer ?
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/maay-dev/2005-November/index.html" >
   <LINK REL="made" HREF="mailto:maay-dev%40lists.berlios.de?Subject=Re%3A%20%5BMaay-dev%5D%20new%20bug%20in%20indexer%20%3F&In-Reply-To=%3C35cde7700511030729y2559876o74bcf0f67d97b8a6%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   
   <LINK REL="Next"  HREF="000018.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Maay-dev] new bug in indexer ?</H1>
    <B>Fr&#233;d&#233;ric Dang Ngoc</B> 
    <A HREF="mailto:maay-dev%40lists.berlios.de?Subject=Re%3A%20%5BMaay-dev%5D%20new%20bug%20in%20indexer%20%3F&In-Reply-To=%3C35cde7700511030729y2559876o74bcf0f67d97b8a6%40mail.gmail.com%3E"
       TITLE="[Maay-dev] new bug in indexer ?">frederic.dangngoc at gmail.com
       </A><BR>
    <I>Thu Nov  3 16:29:30 CET 2005</I>
    <P><UL>
        
        <LI>Next message: <A HREF="000018.html">[Maay-dev] new bug in indexer ?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17">[ date ]</a>
              <a href="thread.html#17">[ thread ]</a>
              <a href="subject.html#17">[ subject ]</a>
              <a href="author.html#17">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

I have just updated the maay source from the subversion repository
and I have this error when launching the indexer. Any ideas ?

Traceback (most recent call last):
  File &quot;indexer.py&quot;, line 326, in ?
    run()
  File &quot;indexer.py&quot;, line 318, in run
    indexer.start()
  File &quot;indexer.py&quot;, line 115, in start
    existingFiles = self.runIndexer(isPrivate=True)
  File &quot;indexer.py&quot;, line 154, in runIndexer
    state=state))
  File &quot;indexer.py&quot;, line 174, in indexDocument
    self.serverProxy.indexDocument(self.cnxId, futureDoc)
  File &quot;/usr/lib/python2.4/xmlrpclib.py&quot;, line 1096, in __call__
    return self.__send(self.__name, args)
  File &quot;/usr/lib/python2.4/xmlrpclib.py&quot;, line 1377, in __request
    allow_none=self.__allow_none)
  File &quot;/usr/lib/python2.4/xmlrpclib.py&quot;, line 1029, in dumps
    data = m.dumps(params)
  File &quot;/usr/lib/python2.4/xmlrpclib.py&quot;, line 603, in dumps
    dump(v, write)
  File &quot;/usr/lib/python2.4/xmlrpclib.py&quot;, line 613, in __dump
    raise TypeError, &quot;cannot marshal %s objects&quot; % type(value)
TypeError: cannot marshal &lt;class 'maay.dbentity.FutureDocument'&gt; objects

--
Fr&#233;d&#233;ric Dang Ngoc

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	
	<LI>Next message: <A HREF="000018.html">[Maay-dev] new bug in indexer ?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#17">[ date ]</a>
              <a href="thread.html#17">[ thread ]</a>
              <a href="subject.html#17">[ subject ]</a>
              <a href="author.html#17">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/maay-dev">More information about the Maay-dev
mailing list</a><br>
</body></html>
